title: Flyaway.css
email: shenlu89dev@gmail.com
description: "Flyaway.css is a css3 animation tool, which can help you create an vivid paper-plane animation. /* Flyaway.css was inspired by @Adrian Del Balso and based on Bootstrap and Font Awesome. */"

url: "http://takentech.com/flyaway"
highlighter: pygments
markdown: redcarpet
